### ISSUE TITLE
Cannot build with `rake` on 7.2 <= Xcode < 7.3 on Yosemite and El Cap

### ISSUE THREAD

**Issue by jmoody** [specta/specta#206]
This a bit of moot point since most users have migrated to El Cap and Xcode 7.3, but I wanted to bring it up anyway because some of us have to live in Yosemite for a while longer which means living with Xcode 7.2*. 

I don't expect a fix.  I want to make a note of the defect so that others can quickly find a workaround.

I think the only action items here:
- Update Travis to run Xcode 7.3 with `osx_image: xcode7.3` to get coverage on the most recent version of Xcode
- Update the README to say building `rake` on Xcode 7.2 is not supported
### Reproduce

```
$ bundle install
$ DEVELOPER_DIR=/Xcode/7.2.1/Xcode.app/Contents/Developer bundle exec rake
```
### Expected

To build the libraries for MacOS and iOS.
### Found

```
Running xcrun xcodebuild -workspace Specta.xcworkspace \
   -scheme Specta-iOS \
   -sdk iphonesimulator \
   -configuration Release \
   SYMROOT=build

/Xcode/7.2.1/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'; did you mean 'uint64_t'?
** BUILD FAILED **
```

I believe the problem is that Foundation, Security, and other frameworks are not being found and linked.  I didn't want to spend too much time debugging since there is a workaround.  I tried playing with the `xcodebuild` commands but nothing obvious worked. The Calabash organization had a difficult time transition our build system from Xcode 7.0 => 7.1 => 7.2 so I am familiar with some of the problems associated with distributing libraries.
### Workaround

Build with Xcode 7.1.1 on Yosemite or Xcode 7.3 on El Cap.
### Tests

```
- [x] Xcode 7.0.1 # Used on Travis
- [x] Xcode 7.1.1
- [ ] Xcode 7.2  **FAILED**  Tested on El Cap and Yosemite
- [ ] Xcode 7.2.1 **FAILED**
- [x] Xcode 7.3 (El Cap)
```
